## These functions cache matrix and its inverse in an alternate environment

## makeCacheMatrix initializes an object that stores the matrix and its inverse
##   in a cached environment
## It takes a square matrix x as argument
## It returns with the lsit of methods implemented by the function
## 1 - set - sets the square matrix in the cached environment
## 2 - get - gets the square matrix from the cached environment
## 3 - setinverse - sets the inverse in the cached environment
## 4 - get inverse - gets the inverse from the cached environment

makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    set <- function(y){
        x <<- y
        inv <<- NULL
    }
    get <- function() x
    setinverse <- function(inverse) inv <<- inverse
    getinverse <- function() inv
    list(set = set, get = get, setinverse = setinverse, getinverse = getinverse)
}


## cacheSolve computes the inverse of the square matrix stored in the cached 
##   environment
## It takes the list generated by makeCacheMatrix caching of the original square
##   matrix
## Returns the inverse of the square matrix

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    inv <- x$getinverse()
    if (!is.null(inv)) {
        message("getting cached data")
        return (inv)
    }
    data <- x$get()
    inv <- solve(data, ...)
    x$setinverse(inv)
    inv
}
